server:
  host: "0.0.0.0"
  port: 51820
  cert_file: "certs/server.crt"
  key_file: "certs/server.key"

client:
  server_address: "127.0.0.1:51820"
  device_name: "sd-wan0"
  mtu: 1500

network:
  subnet: "10.0.0.0/24"
  dns: "8.8.8.8"
  keep_alive: 30
  reconnect: 5

nat:
  relay_server: "127.0.0.1"
  relay_port: 51821 